Fix Docker Compose and Deployement

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,6 +20,24 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           source: "."
           target: "~/repo"
+      
+      - name: Check and install Docker and Docker Compose if needed
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USER }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
+            if ! docker-compose --version > /dev/null 2>&1; then
+              echo "docker-compose not found, installing Docker and Docker Compose..."
+              sudo apt update -y
+              sudo apt upgrade -y
+              sudo apt install docker.io -y
+              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+              sudo chmod +x /usr/local/bin/docker-compose
+            else
+              echo "docker-compose is already installed."
+            fi
 
       - name: Create .env file on the server
         uses: appleboy/ssh-action@master
